query GetPokemonsByGame($gen: Int) {
  pokemons: pokemon_v2_pokemonspecies(
    where: { pokemon_v2_generation: { id: { _lte: $gen } } }
    order_by: { id: asc }
  ) {
    name
    id
    typesData: pokemon_v2_pokemons {
      types: pokemon_v2_pokemontypes {
        id: type_id
      }
    }
  }
}
